import { Parser } from '@etothepii/satisfactory-file-parser';
import { readFileSync } from 'fs';
import { join } from 'path';
import { buildInstanceMap, parseStacks, itemDisplayName, type InventoryItem } from './storage';
import { buildClassFromTypePath, buildingLabel } from './buildings';

type SatisfactorySave = ReturnType<typeof Parser.ParseSave>;

// ── Recipe catalog (generated by generate_recipes.py) ───────────────────────
interface RecipeItem { item: string; name: string; amount: number; fluid: boolean; }
interface Recipe {
  name: string;
  durationSec: number;
  ingredients: RecipeItem[];
  products: RecipeItem[];
  producedIn: string[];
}
let _recipes: Record<string, Recipe> | null = null;
function getRecipes(): Record<string, Recipe> {
  if (!_recipes) {
    try {
      _recipes = JSON.parse(readFileSync(join(__dirname, '../../../data/recipes.json'), 'utf-8'));
    } catch {
      _recipes = {};
    }
  }
  return _recipes!;
}

// Item catalog → authoritative display names (so e.g. Desc_WAT1 reads "Somersloop"
// rather than the class-name fallback "W A T1"). Applied over parsed buffer stacks.
let _items: Record<string, { name: string }> | null = null;
function getItems(): Record<string, { name: string }> {
  if (!_items) {
    try {
      _items = JSON.parse(readFileSync(join(__dirname, '../../../data/items.json'), 'utf-8'));
    } catch {
      _items = {};
    }
  }
  return _items!;
}
function withNames(items: InventoryItem[]): InventoryItem[] {
  const cat = getItems();
  for (const it of items) it.displayName = cat[it.itemClass]?.name ?? it.displayName;
  return items;
}

// ── Machine class universe (read-only inspector) ────────────────────────────
const PRODUCTION_CLASSES = new Set([
  'Build_SmelterMk1', 'Build_FoundryMk1', 'Build_ConstructorMk1', 'Build_AssemblerMk1',
  'Build_ManufacturerMk1', 'Build_OilRefinery', 'Build_Packager', 'Build_Blender',
  'Build_HadronCollider', 'Build_QuantumEncoder', 'Build_Converter',
]);

// Static base power output (MW) — not stored in the save. GeoThermal is variable
// (omitted → no figure shown).
const GENERATOR_MW: Record<string, number> = {
  Build_GeneratorBiomass: 30,
  Build_GeneratorCoal:    75,
  Build_GeneratorFuel:    250,
  Build_GeneratorNuclear: 2500,
};

// Static base power *consumption* (MW at 100% clock, no somersloop) for fixed-power
// production machines. Variable-power machines (Particle Accelerator / Quantum
// Encoder / Converter) draw a recipe-dependent range → omitted (no figure shown).
const PRODUCTION_BASE_POWER: Record<string, number> = {
  Build_SmelterMk1:     4,
  Build_FoundryMk1:     16,
  Build_ConstructorMk1: 4,
  Build_AssemblerMk1:   15,
  Build_ManufacturerMk1: 55,
  Build_OilRefinery:    30,
  Build_Packager:       10,
  Build_Blender:        75,
};
// Overclock scales power by clock^1.321928; somersloop production boost scales it
// by boost² (full amplification = 2× output, 4× power).
function productionPowerMW(buildClass: string, clock: number, boost: number): number | null {
  const base = PRODUCTION_BASE_POWER[buildClass];
  if (base === undefined) return null;
  return Math.round(base * Math.pow(clock, 1.321928) * boost * boost * 10) / 10;
}
const GENERATOR_CLASSES = new Set([...Object.keys(GENERATOR_MW), 'Build_GeneratorGeoThermal']);

const EXTRACTOR_CLASSES = new Set([
  'Build_MinerMk1', 'Build_MinerMk2', 'Build_MinerMk3',
  'Build_WaterPump', 'Build_OilPump', 'Build_FrackingExtractor',
]);

export function isInspectableMachineClass(buildClass: string): boolean {
  return PRODUCTION_CLASSES.has(buildClass) || GENERATOR_CLASSES.has(buildClass)
    || EXTRACTOR_CLASSES.has(buildClass);
}

// ── Output shape (discriminated; instanceName is the stable edit key) ────────
export interface MachineOutputItem extends RecipeItem { perMin: number; }
export interface MachineInstance {
  instanceName: string;
  pos: { x: number; y: number; z: number };
  kind: 'production' | 'generator' | 'extractor';
  isProducing: boolean;
  // production
  recipeClass?: string | null;
  recipeName?: string | null;
  recipeDurationSec?: number;
  progressPct?: number;     // current craft-cycle progress (0–100) at save time
  clockPct?: number;
  boostPct?: number;
  inputs?: RecipeItem[];
  outputs?: MachineOutputItem[];
  inputBuffer?: InventoryItem[];
  outputBuffer?: InventoryItem[];
  // mInventoryPotential — holds power shards (Desc_CrystalShard, overclock) and
  // somersloops (Desc_WAT1, production boost) in one component.
  potential?: InventoryItem[];
  potentialSlots?: number;
  // generator
  fuelClass?: string | null;
  fuelName?: string | null;
  powerMW?: number | null;  // generator: output MW · production: estimated draw MW
  fuelBuffer?: InventoryItem[];
  // extractor
  resourceClass?: string | null;
  resourceName?: string | null;
}

// Strip a UE object path to its class stem: ".../Recipe_X.Recipe_X_C" → "Recipe_X".
function classStem(pathName: string): string {
  return pathName.split('.').pop()?.replace(/_C$/, '') ?? '';
}

function refEntity(byInstance: Map<string, any>, prop: any): any {
  const ref = prop?.value?.pathName;
  return ref ? byInstance.get(ref) : null;
}

function transformPos(obj: any): { x: number; y: number; z: number } {
  const t = obj?.transform?.translation ?? {};
  return { x: t.x ?? 0, y: t.y ?? 0, z: t.z ?? 0 };
}

export function extractMachineInstances(save: SatisfactorySave, buildClass: string): MachineInstance[] {
  if (!isInspectableMachineClass(buildClass)) return [];
  const byInstance = buildInstanceMap(save);
  const recipes = getRecipes();
  const out: MachineInstance[] = [];

  for (const obj of byInstance.values()) {
    if (buildClassFromTypePath(obj.typePath ?? '') !== buildClass) continue;
    const p = obj.properties ?? {};
    const base = {
      instanceName: obj.instanceName as string,
      pos: transformPos(obj),
      isProducing: !!p.mIsProducing?.value,
    };

    if (PRODUCTION_CLASSES.has(buildClass)) {
      const clock = p.mCurrentPotential?.value ?? 1;
      const boost = p.mCurrentProductionBoost?.value ?? 1;
      const recipeClass = p.mCurrentRecipe?.value?.pathName ? classStem(p.mCurrentRecipe.value.pathName) : null;
      const recipe = recipeClass ? recipes[recipeClass] : null;
      const outputs: MachineOutputItem[] = (recipe?.products ?? []).map(prod => ({
        ...prod,
        perMin: recipe!.durationSec > 0 ? (prod.amount / recipe!.durationSec) * 60 * clock * boost : 0,
      }));
      const potential = parseStacks(refEntity(byInstance, p.mInventoryPotential));
      out.push({
        ...base,
        kind: 'production',
        recipeClass,
        recipeName: recipe?.name ?? null,
        recipeDurationSec: recipe?.durationSec ?? 0,
        progressPct: Math.round((p.mCurrentManufacturingProgress?.value ?? 0) * 100),
        powerMW: productionPowerMW(buildClass, clock, boost),
        clockPct: Math.round(clock * 100),
        boostPct: Math.round(boost * 100),
        inputs: recipe?.ingredients ?? [],
        outputs,
        inputBuffer: withNames(parseStacks(refEntity(byInstance, p.mInputInventory)).contents),
        outputBuffer: withNames(parseStacks(refEntity(byInstance, p.mOutputInventory)).contents),
        potential: withNames(potential.contents),
        potentialSlots: potential.totalSlots,
      });
    } else if (GENERATOR_CLASSES.has(buildClass)) {
      const fuelPath = p.mCurrentFuelClass?.value?.pathName ?? '';
      out.push({
        ...base,
        kind: 'generator',
        fuelClass: fuelPath ? classStem(fuelPath) : null,
        fuelName: fuelPath ? itemDisplayName(fuelPath) : null,
        powerMW: GENERATOR_MW[buildClass] ?? null,
        fuelBuffer: withNames(parseStacks(refEntity(byInstance, p.mFuelInventory)).contents),
      });
    } else {
      // extractor
      const clock = p.mCurrentPotential?.value ?? 1;
      const outputBuffer = withNames(parseStacks(refEntity(byInstance, p.mOutputInventory)).contents);
      const res = outputBuffer[0];
      out.push({
        ...base,
        kind: 'extractor',
        clockPct: Math.round(clock * 100),
        resourceClass: res?.itemClass ?? null,
        resourceName: res?.displayName ?? null,
        outputBuffer,
      });
    }
  }

  // Stable order (matches the buildings tab's instance order closely enough for
  // position-matching; sort by name for determinism).
  out.sort((a, b) => a.instanceName.localeCompare(b.instanceName));
  return out;
}

// label re-exported for callers that want a human title without importing buildings.
export { buildingLabel };
