#!/usr/bin/env python3
"""
Extract resource node data from FModel-exported Persistent_Level.json.

Source: FactoryGame/Content/FactoryGame/Map/GameLevel01/Persistent_Level.json
Generated by FModel with GAME_UE5_6 and FactoryGame.usmap loaded.

All 625 resource node actors are in this single file with:
  - mResourceClass (ObjectName contains the Desc_ class)
  - mPurity (RP_Pure / RP_Inpure / absent = RP_Normal default)
  - Position via child BoxComponent RelativeLocation

Geysers have no mResourceClass (they are not minable resources).
"""

import json
import re
from pathlib import Path
from collections import Counter

from _paths import CONTENT, BACKEND_DATA  # noqa: E402

LEVEL_JSON = CONTENT / 'FactoryGame' / 'Map' / 'GameLevel01' / 'Persistent_Level.json'
OUT_JSON   = BACKEND_DATA / 'resource-nodes.json'

NODE_TYPES = {
    'BP_ResourceNode_C',
    'BP_ResourceNodeGeyser_C',
    'BP_FrackingCore_C',
    'BP_FrackingSatellite_C',
}

PURITY_MAP = {
    'RP_Pure':   'Pure',
    'RP_Inpure': 'Impure',
    'RP_Normal': 'Normal',
}

# Extract Desc_XXX from ObjectName like "BlueprintGeneratedClass'Desc_OreIron_C'"
DESC_RE = re.compile(r"'(Desc_[A-Za-z0-9]+)_C'")


def parse_resource_class(obj_name: str) -> str:
    m = DESC_RE.search(obj_name)
    return m.group(1) if m else ''


def main():
    print(f'Loading {LEVEL_JSON}...')
    data = json.load(open(LEVEL_JSON))

    # Index all objects by (Outer, Name) for fast child lookup
    by_outer_name: dict[tuple, dict] = {}
    for item in data:
        key = (item.get('Outer', ''), item.get('Name', ''))
        by_outer_name[key] = item

    nodes = [item for item in data if item.get('Type') in NODE_TYPES]
    print(f'Found {len(nodes)} resource node actors')

    result: dict[str, dict] = {}

    for actor in nodes:
        name  = actor['Name']
        atype = actor['Type']
        props = actor.get('Properties', {})

        # Resource class
        rc_obj = props.get('mResourceClass', {})
        resource = parse_resource_class(rc_obj.get('ObjectName', '')) if isinstance(rc_obj, dict) else ''

        # Purity (absent = RP_Normal default)
        purity = PURITY_MAP.get(props.get('mPurity', 'RP_Normal'), 'Normal')

        # Position: on child BoxComponent / SceneComponent
        pos = {'x': 0.0, 'y': 0.0, 'z': 0.0}
        root_ref = props.get('RootComponent', {})
        if isinstance(root_ref, dict):
            comp_name = root_ref.get('ObjectName', '').split('.')[-1].rstrip("'")
            child = by_outer_name.get((name, comp_name))
            if child:
                loc = child.get('Properties', {}).get('RelativeLocation', {})
                if isinstance(loc, dict):
                    pos = {
                        'x': round(loc.get('X', 0.0), 2),
                        'y': round(loc.get('Y', 0.0), 2),
                        'z': round(loc.get('Z', 0.0), 2),
                    }

        bp_type = atype.replace('_C', '').replace('BP_', '')

        result[f'PersistentLevel.{name}'] = {
            'instance': f'PersistentLevel.{name}',
            'bpType':   bp_type,
            'resource': resource,
            'purity':   purity,
            'position': pos,
        }

    OUT_JSON.write_text(json.dumps(result, indent=2))

    total  = len(result)
    typed  = sum(1 for v in result.values() if v['resource'])
    pure   = sum(1 for v in result.values() if v['purity'] == 'Pure')
    impure = sum(1 for v in result.values() if v['purity'] == 'Impure')
    normal = sum(1 for v in result.values() if v['purity'] == 'Normal')

    print(f'\nDone: {total} nodes, {typed} with resource class ({100*typed//total}%)')
    print(f'Purity: {normal} Normal, {pure} Pure, {impure} Impure')
    print(f'Saved to {OUT_JSON}')

    res_counts = Counter(v['resource'] or 'unknown' for v in result.values())
    for res, count in sorted(res_counts.items(), key=lambda x: -x[1]):
        print(f'  {res}: {count}')


if __name__ == '__main__':
    main()
